### ISSUE TITLE
How to expand and support other latex styles?

### ISSUE THREAD

**Issue by yushaw** [raineszm/obsidian-latex-environments#15]
I want to add some prooftree to the note. But it's not supported.

Is there any way to expand the environment? thanks

http://math.ucsd.edu/~sbuss/ResearchWeb/bussproofs/

**Comment by raineszm** [comment]
Sorry for the delayed response. I unfortunately don't have control over what environments Obsidian supports. That is set by the built in MathJax plugin. 

You should be able to add proof tree environments with this plugin but they won't render if mathjax doesn't support them.
