### ISSUE TITLE
Not working with live preview

### ISSUE THREAD

**Issue by ndharari** [raineszm/obsidian-latex-environments#17]
The plugin is not working in the new update, the commands do not appear in the command pallete

**Comment by raineszm** [comment]
Sorry. This is due to live preview using CodeMirror6 while this plugin was using some of the CodeMirror5 internals. I'm working on porting to use obsidian's compatibility layer but there is some functionality that isn't exposed. I'll probably roll by own version independent solution for those bits, but it may take a little bit of time.

**Comment by ndharari** [comment]
Great man, keep up the excellent job!

**Comment by ndharari** [comment]
Any news? Loved your pluggin!

**Comment by brianbecsi** [comment]
Great, thank you!

**Comment by raineszm** [comment]
I have packaged up a prerelease of my rewrites. Would anyone be willing to install this using the manual install method in the readme and just test it out a bit?

[obsidian-latex-environments-0.3.0-0.zip](https://github.com/raineszm/obsidian-latex-environments/files/8044608/obsidian-latex-environments-0.3.0-0.zip)

**Comment by ndharari** [comment]
I'll let a try and ley you know!

**Comment by ndharari** [comment]
I did only a little bit of testing but for now its working great. 
Only one bug: double input environments are not deleting correctly, so 
```
\begin{alignedat}{2} -->  2} 
\end{array}{rlrl}  --> rlrl} 
```
on both begin and end statements the deletion bug is the same

**Comment by raineszm** [comment]
Thanks for the testing! Is the latter valid latex? I believe this is related to #8. Supporting environments with multiple arguments is definitely planned but I'm not sure it should delay this release. That being said, even if they are not supported, the extra brace getting deleted is a bug. I'll try to iron that at some of the whitespace bugs I'm seeing out over the next couple days.
