### ISSUE TITLE
add option to disable tab to add `&`

### ISSUE THREAD

**Issue by dtinhvo** [raineszm/obsidian-latex-environments#30]
Tab is a very special key that can conflict with many other plugins, and especially Latex Suite enables cursor jumping with tab. Meanwhile, & is easy to type. I would like an option to disable the tab to add `&` behavior of this plugin.

**Comment by raineszm** [comment]
I'm pretty sure that keybinding must be coming from elsewhere in your set up. This plugin doesn't provide any keybindings. Do you still have that behavior if you disable the obsidian-latex-environments plugin?

**Comment by dtinhvo** [comment]
You are right, this behavior is caused by Latex Suite
